### PR TITLE
Add Docker

### PR DESCRIPTION
**Pull request by aphex3k**
This will add a `Dockerfile` that can be used to build and publish a container.

You can try the container I built from this file like so:
```
docker run --rm ghcr.io/aphex3k/raiju:latest
```

You can build and publish your own package like so:
```
docker buildx build --platform linux/amd64,linux/ppc64le,linux/s390x,linux/arm/v7,linux/arm64/v8 -t "ghcr.io/nyonson/raiju:latest"  --push .
```

If you do not have buildx set up, do that like so:
```
docker buildx create --use 
```

### CODE REVIEW

**Comment by aphex3k** [comment]
If you want to build the container as part of a github action, check this out: https://github.com/aphex3k/nutstash-wallet/blob/main/.github/workflows/ghcr-release.yml

**Comment by aphex3k** [comment]
`reaper` runs without issues on umbrel like so:
```
➜  ~ docker run -it --rm --network="umbrel_main_network" --add-host=umbrel.local:192.168.1.233 --add-host=umbrel-vm.local:10.21.21.9 --add-host=10.21.21.9:10.21.21.9 -v /home/umbrel/umbrel/app-data/lightning/data/lnd:/root/.lnd:ro ghcr.io/aphex3k/raiju:latest -host 10.21.21.9:10009 reaper

Channel ID          Alias                       Capacity (BTC)
841272630381576192  02115a88404ded6c0ffd        0.01
840259980142313474  JayhawkPleb                 0.02
840955970982903808  sphinxrouting-fceb9955a9    0.0007
840259980142313473  BTS_lightning               0.01
787806678450896898  ICanHasSats                 0.02
848253429815967745  LQwD-Indonesia              0.05
825037241643040769  UmbrelReach                 0.01102674
848306206208884736  albatross                   0.05
837739899518910464  Dagnela 🦄 Hunter            0.01
849623421174611968  0349ae4f721fb4a81c3a        0.01
838042265242435585  rickyspanish                0.015
778740105597222913  ln.nicehash.com [Nicehash]  0.005
843112113291526145  0/0_001 Fee | Baby Shark    0.02561024
792355358029840384  gameb_2                     0.001
840259980142313475  be-kind_ZA🇿🇦                0.02
837750894672084993  EchoSixAlphaSix             0.01

```

**Comment by nyonson** [comment]
This is dope thanks! I need to read up on some more container stuff for publishing. Was also curious how the creds would be passed in, but I think this PR is enough docs for now.

**Comment by aphex3k** [comment]
> This is dope thanks! I need to read up on some more container stuff for publishing. Was also curious how the creds would be passed in, but I think this PR is enough docs for now.

The credentials for the github action are auto-generated each time you launch the action.

**Comment by nyonson** [comment]
I added a target to the `justfile` for publishing which I will just run locally for now, but a github action would be slick. Also added some notes to the readme.

**Pull request merged**
